export const ALL_COUNTRYS = "ALL_COUNTRYS "
export const ID_COUNTRY = "ID_COUNTRY "
export const SEARCH = "SEARCH"
export const FILTER = "FILTER"
export const GET_ACTIVITY = "GET_ACTIVITY"
export const FILTER_ACTIVITY = "FILTER_ACTIVITY"
export const ORDER_A_Z = "ORDER_A_Z"
export const ORDER_POBLACION = "ORDER_POBLACION"
export const FORM = "FORM"
export const SAVE_PREVIOUS_STATE = "SAVE_PREVIOUS_STATE"

